# Generated by Django 2.1 on 2018-10-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='movies',
            field=models.ManyToManyField(to='api.Movie'),
        ),
    ]
